mlp:
  player: 0
  key: 1
  apple: 2

  #Without walls for early testing
cnn_simple:
  floor: [1, 1, 1]
  apple: [1, 0, 1]
  player: [1, 0, 0]
  key: [0, 1, 0]
  lock: [0, 0, 1]
cnn_extra_colours_pack:
  - [0.5, 0.5, 0.5]
  - [0, 1, 1]
  - [1, 0, 1]
  - [1, 1, 0]
hyperparams:
  lr: 1.0e-03
  gamma: 0.99
  lambda: 0.93
  value_loss_coef: 0.7
  policy_loss_coef: 1
  entropy_loss_coef: 0.08
  elc_diminish_rate: 0.99
  episodes_per_elc_reduction: 4
  episodes_per_gif_gen: 64
  curriculum_lengthths:
    - 500
